[package]
name = "destream_json"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
license = "Apache-2.0"
description = "Library for decoding & encoding a JSON stream"
repository = "http://github.com/haydnv/destream_json"
readme = "README.md"

categories = ["asynchronous", "encoding", "parser-implementations", "parsing", "web-programming"]
keywords = ["json", "stream", "serialize", "deserialize"]


[dependencies]
async-trait = "0.1"
base64 = "0.13"
destream = "0.1"
futures = "0.3"
pin-project = "1.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros"] }
tokio-test = "0.4"
