[package]
name = "destream_json"
version = "0.10.2"
authors = ["code@tinychain.net"]
edition = "2021"
license = "Apache-2.0"
description = "Library for decoding & encoding a JSON stream"
repository = "https://github.com/haydnv/destream_json"
readme = "README.md"

categories = ["asynchronous", "encoding", "parser-implementations", "parsing", "web-programming"]
keywords = ["json", "stream", "serialize", "deserialize"]

[features]
default = []
tokio-io = ["tokio/io-util"]
value = ["number-general/stream"]
all = ["tokio-io", "value"]

[dependencies]
async-trait = "0.1"
base64 = "0.21"
bytes = "1.0"
destream = { path = "../destream" }
futures = "0.3"
number-general = { path = "../number-general", optional = true }
pin-project = "1.0"
tokio = { version = "1.25", features = ["io-util"], optional = true }
uuid = "1.2"

[dev-dependencies]
number-general = { path = "../number-general", features=["stream"] }
tokio = { version = "1.25", features = ["fs", "macros"] }
tokio-util = { version = "0.7", features = ["io"] }
tokio-test = "0.4"
