[package]
name = "destream_json"
version = "0.9.0"
authors = ["haydn@tinychain.net"]
edition = "2018"
license = "Apache-2.0"
description = "Library for decoding & encoding a JSON stream"
repository = "https://github.com/haydnv/destream_json"
readme = "README.md"

categories = ["asynchronous", "encoding", "parser-implementations", "parsing", "web-programming"]
keywords = ["json", "stream", "serialize", "deserialize"]

[features]
default = []
tokio-io = ["tokio/io-util"]
value = ["number-general"]
all = ["tokio-io", "value"]

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
destream = "0.5"
futures = "0.3"
number-general = { version = "0.8", features=["stream"], optional = true }
pin-project = "1.0"
tokio = { version = "1.17", features = ["io-util"], optional = true }

[dev-dependencies]
number-general = { version = "0.8", features=["stream"] }
tokio = { version = "1.17", features = ["fs", "macros"] }
tokio-util = { version = "0.7", features = ["io"] }
tokio-test = "0.4"
