[package]
name = "destream_json"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
license-file = "LICENSE"
description = "Library for decoding & encoding a JSON stream"
repository = "http://github.com/haydnv/destream_json"
readme = "README.md"

categories = ["asynchronous", "encoding", "parser-implementations", "parsing", "rust-patterns", "web-programming"]
keywords = ["json", "stream", "streaming", "serialize", "deserialize"]


[dependencies]
async-trait = "0.1"
destream = {path = "../destream"}
futures = "0.3"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros"] }
tokio-test = "0.4"
