[package]
name = "destream_json"
version = "0.5.3"
authors = ["haydnv"]
edition = "2018"
license = "Apache-2.0"
description = "Library for decoding & encoding a JSON stream"
repository = "http://github.com/haydnv/destream_json"
readme = "README.md"

categories = ["asynchronous", "encoding", "parser-implementations", "parsing", "web-programming"]
keywords = ["json", "stream", "serialize", "deserialize"]

[features]
default = []
tokio-io = ["tokio/io-util"]
all = ["tokio-io"]

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
destream = "0.3"
futures = "0.3"
pin-project = "1.0"
tokio = { version = "1.2", features = ["io-util"], optional = true }

[dev-dependencies]
tokio = { version = "1.2", features = ["macros"] }
tokio-test = "0.4"
