# from https://pratikpc.medium.com/publishing-crates-using-github-actions-165ee67780e1

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*" # Push events to every tag not containing /

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check if token in environment
        run: ${{ secrets.CRATES_TOKEN }} == '' && echo "No token in environment, exiting" && exit 1

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
